const { type } = require("@testing-library/user-event/dist/type");
const mongoose=require("mongoose");

const courseSchema=new mongoose.Schema({
    courseName:{
        type:String,
        trim:true,
        required:true
    },
    courseDescription:{
        type:String,
        required:true,
        trim:true
    },
    instructor:{
        type:mongoose.Schema.Types.ObjectId,
        required:true,
        ref:"User",
    },
    whatyouwilllearn:{
        type:String,
        requierd:true,
        trim:true
    },
    coursecontent:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"Section"
        }
    ],
    ratingandreviews:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"RatingAndReviews",
        }
    ],
    duration:{
        type:String,
        requierd:true
    },
    price:{
        type:Number,
        requierd:true,
    },
    thumbnail:{
        type:String,
        requierd:true,
    },
    category:{
        type:mongoose.Schema.Types.ObjectId,
        ref:"Category"
    },
    tag:
        {
            type:String,
            required:true
        }
    ,
    instructions:
        {
            type:String,
            required:true
        }
    ,
    studentsenroll:[
        {
            type:mongoose.Schema.Types.ObjectId,
            ref:"User"
        }
    ],
    status:{
        type:String,
        default:"Draft"
    },
    time:{
        type:Date,
        default:Date.now()
    }
})
module.exports=mongoose.model("Course",courseSchema);